name: CI - Next.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    env:
      PUSHER_APP_ID: ${{ secrets.PUSHER_APP_ID }}
      PUSHER_KEY: ${{ secrets.PUSHER_KEY }}
      PUSHER_SECRET: ${{ secrets.PUSHER_SECRET }}
      PUSHER_CLUSTER: ${{ secrets.PUSHER_CLUSTER }}
      NEXT_PUBLIC_PUSHER_KEY: ${{ secrets.NEXT_PUBLIC_PUSHER_KEY }}
      NEXT_PUBLIC_PUSHER_CLUSTER: ${{ secrets.NEXT_PUBLIC_PUSHER_CLUSTER }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: TypeScript check
        run: npx tsc --noEmit

      - name:  Build Next.js app
        run: npm run build

  
